version: '3.8'

services:
    frontend:
      build: ./example-frontend
      ports:
        - "3000:5000"
    backend:
       build: ./example-backend
       ports:
         - "8080:8080"
       environment:
         - REDIS_HOST=redis
    redis:
       image: redis:latest
