version: '3.8'

services:
    frontend:
      build: ./example-frontend
      ports:
        - "3000:5000"
    backend:
       build: ./example-backend
       ports:
         - "8080:8080"
       environment:
         - REDIS_HOST=redis
         - POSTGRES_HOST=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DATABASE=postgres
    redis:
       image: redis:latest
    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
